feat(world-loader): load gltf
SuteraVR/VanillaClient pull request #5
Opened 2024-07-14 10:39 UTC by LegitYew0108

- close #3 #2 #4
yamlファイルを読んで、yamlファイルで指定されたgltfファイルを読めるところまでやります。

2024-07-14 10:41 UTC, LegitYew0108 commented
glTFの読み込み、移動、回転はできてます
あとはyamlを読み込んで、ワールド上に表すのみ

2024-07-15 15:17 UTC, LegitYew0108 commented
最小構成のyaml読むやつはできました
ただ、エラーハンドリングがグッチャグチャなのでそこ訂正します

2024-07-19 01:07 UTC, LegitYew0108 commented
yamlよんでglTF読み込みはできた！
物体の位置移動がなんかできてないのでそこは修正必須
gltf.rsのエラーハンドリングもちゃんとできていないので修正します

2024-09-02 02:31 UTC, LegitYew0108 commented
yaml_loaderのエラーハンドリングを整えました
これでだいぶ見やすくなったはず

2024-09-02 16:47 UTC, LegitYew0108 commented
clippyに言われた部分を直した
rustfmtかけて整えた

2024-09-14 11:54 UTC, AsPulse requested changes

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/gltf.rs
> +        }
let-else使いましょう！これも悪くはないんだけどね……

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/gltf.rs
> +        );
transformが`[f32; 10]`という曖昧な型になっているのがよくないです
具体的な名前付きの構造体にしてもいいし、行列として扱ってるならNewTypeパターンでそれも明確にしましょう
ここらへんも本来はDisplayトレイトのお仕事ですので、transform内からPositionを生成できるようにして、それにDisplayトレイトを実装しましょう (こういうところに表示するロジックが混入してくるのがよくないです)

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/yaml_loader.rs
> +        };
ここらへんも同じくlet-else使いましょう！

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/yaml_loader.rs
> +            Some(model_type) if model_type.as_str().unwrap() == "gltf" => {
InvalidSuteraFormatErrあるんだから、どうせならここもunwrapではなくそれを返しませんか……？

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/yaml_loader.rs
> +                };
ここも let-else使いどころ！

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/yaml_loader.rs
> +                return Err(e);
ここあれですか？エラー表示したい感じですか……？
基本的にはエラーの表示ってここらへんにはいらないけど……

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/yaml_loader.rs
> +}
ここらへんもlet-elseです！
一つ気になるとすれば、InvalidSuteraFormatErrがなんかちょっと微妙か……？
エラーの補足情報として、yamlのパスとかも必要な気がするし、`xxx key was not found.`というエラー文をくりかえしすぎです。InvalidSuteraFormatErrも別のerrorとして、KeysNotFoundエラーとかにするべきだと思います。(thiserrorクレートの使いこなしですね……)

そもそも、serde使えば……という話ではあるんだけどさ……

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/yaml_loader.rs
> +}
ErrorとErrが混ざってるから何も言われないんだと思うんですが、
RustではEnumのvariantの語尾に同じ単語がたくさんひっついてるとそれつける意味なくね？と教えてくれるはずです

`InvalidYamlPath`,`InvalidSuteraFormat` みたいなvariant名にすべきですね

2024-09-14 11:54 UTC, AsPulse commented on rust/src/world/yaml_loader.rs
> +                }
ここの謎の型変換は……？
transformをf64で保持するのは厳しいんですか……？ (godot側がf32とか？)

2024-09-14 11:54 UTC, AsPulse commented on rust/src/lib.rs
> +    init_once: bool,
```suggestion
    is_initialized: bool,
    is_inputted: bool,
```
名前がひどいですぽよ……

2024-09-14 12:01 UTC, HMasataka requested changes

2024-09-14 12:01 UTC, HMasataka commented on rust/src/world/yaml_loader.rs
> +#[instrument(skip_all, name = "worldformaterror", level = "trace")]
```suggestion
#[instrument(skip_all, name = "world_format_error", level = "trace")]
```

2024-09-14 12:01 UTC, HMasataka commented on rust/src/world/gltf.rs
> +            self.transform[0],
どこを読みとっているのか分かりづらいのでyamlのフォーマット自体にkeyを設定してあげても良いのかも
このあたりはフォーマット整備するひととも相談になりそうなのでひとまずスルーでもOKです

```yaml
transform:
    x: 0.0
    y: 0.0
    z: 0.0
    ...
```

2024-09-14 12:01 UTC, HMasataka commented on rust/src/world/yaml_loader.rs
> +        .map_err(|e|{SpanErr::from(WorldLoadingError::SerdeYamlLoadingError(e.to_string()))})?;
```suggestion
        .map_err(|e| SpanErr::from(WorldLoadingError::SerdeYamlLoadingError(e.to_string())))?;
```

↑の同じような処理と合わせる意味でこっちの方が良いかも

2024-09-14 12:11 UTC, AsPulse commented on rust/src/world/gltf.rs
> +            self.transform[0],
同じくそう思います (行列を意図しているのでない限り)
これはRustの型システムの観点からみてもそうです
- https://github.com/SuteraVR/VanillaClient/pull/5#discussion_r1759722819

2024-09-14 14:47 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +}
もう少しエラー分に情報載せたほうがいいってことですね。KeysNotFoundエラーは実装します。

serde使えばというのはどういう話...？

2024-09-14 14:49 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +                return Err(e);
エラー処理周りあまり理解できてなくて、以前教えてもらったときのままで書きました。
この処理ってどこでするべきなんですか？

2024-09-14 14:52 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +                }
これは完全にミスです。
なぜかSuteraGltfObjectの方をf32で実装してて、そこに合わせて全部f32になってました。修正しときます。

2024-09-14 14:53 UTC, LegitYew0108 commented on rust/src/lib.rs
> +    init_once: bool,
これはひどい...申し訳ないぽよ........
(試しに1回処理してみようとしたのがずっと残ってました)

2024-09-14 14:56 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +                }
いや、ミスってなかった。
Godot側の[Vector3型](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Vector3.html)や[Quaternion型](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Quaternion.html)がf32で実装されてました...
それに合わせた形ですね

2024-09-14 15:02 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +            Some(model_type) if model_type.as_str().unwrap() == "gltf" => {
[ここで](https://github.com/SuteraVR/VanillaClient/pull/5/commits/e7f2e5639d768e635955e345da8838504950a746)修正しました！

2024-09-14 15:22 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +                return Err(e);
エラー表示の部分ってことはこんな感じに書けばいい感じですか？
```diff yaml_loader.rs
+                let e = SpanErr::from(WorldLoadingError::InvalidObjectTypeErr(
+                    type_str.to_string()
+                ));
-                tracing::error!("{}", e.error);
-                eprintln!("{}", color_spantrace::colorize(&e.span));
+                return Err(e);
```

2024-09-14 15:24 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +                return Err(e);
ここでError型を返して、最後にResultを受け取る部分でエラー表示って認識で合ってるかな...？

2024-09-16 09:27 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +}
ErrとErrorが混ざってるのは気が付かなかった！修正しました。

2024-09-16 09:27 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +#[instrument(skip_all, name = "worldformaterror", level = "trace")]
修正しました！

2024-09-16 09:27 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +        .map_err(|e|{SpanErr::from(WorldLoadingError::SerdeYamlLoadingError(e.to_string()))})?;
修正しました！

2024-09-16 09:38 UTC, LegitYew0108 commented on rust/src/world/gltf.rs
> +            self.transform[0],
可読性向上のためにちょっと長いけどこんな感じにしてみました。
```yaml
      transform:
        position_x: 0
        position_y: 0
        position_z: 0
        rotation_x: 0
        rotation_y: 0
        rotation_z: 0
        rotation_w: 1.0
        scale_x: 1.0
        scale_y: 1.0
        scale_z: 1.0

```

2024-09-16 16:39 UTC, LegitYew0108 commented on rust/src/world/gltf.rs
> +        );
直しました！
ここに関しては`godot::builtin::Transform3D`を使うことを検討したんですが、
- 3次アフィン変換行列だと可読性が落ちそう(パット見じゃわからない)
- あんまり理解できてない
という理由で一旦実装はやめました。

その代わりに`SuteraTransform`という構造体を作って位置(Vector3)、回転(Quaternion)、拡大(Vector3)をまとめました。`godot::builtin::Node3D`にも`SetSuteraTransform`traitでSuteraTransformに沿って位置回転をセットできるようにしてあります。

2024-09-16 16:39 UTC, LegitYew0108 commented on rust/src/world/gltf.rs
> +        }
修正しました！

2024-09-16 16:39 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +        };
修正しました！

2024-09-16 16:39 UTC, LegitYew0108 commented on rust/src/world/yaml_loader.rs
> +                };
修正しました！

2024-09-17 05:17 UTC, AsPulse requested changes
改めて見返すと、serde_yaml使ってる……??
serde_yamlを使わない実装をしているように見えたけどdeserializeしてるし……
ちょっと保留、体育大会終わったらちゃんと見させて

2024-09-17 10:15 UTC, LegitYew0108 commented
了解
一応言うと、serde_yaml使ってる...けど今言われてValue型使う必要が無いことに気づいた
struct使うように書き換えたほうがいいね
ちょっと直してみます

2024-09-18 01:46 UTC, HMasataka approved these changes

2024-09-19 14:56 UTC, AsPulse requested changes
あとこれだけ……！

2024-09-19 14:56 UTC, AsPulse commented on rust/src/world/gltf.rs
> +use godot::classes::{CollisionObject3D, GltfDocument, GltfState};
これは……？何かimportしなきゃいけない理由でも……？

2024-09-19 14:59 UTC, LegitYew0108 commented on rust/src/world/gltf.rs
> +use godot::classes::{CollisionObject3D, GltfDocument, GltfState};
あーここ、使ってないのはCollisionObject3Dだけなんだけど、今後Colliderの追加をするから入れておいてた
必要ない？

2024-09-19 15:03 UTC, AsPulse commented on rust/src/world/gltf.rs
> +use godot::classes::{CollisionObject3D, GltfDocument, GltfState};
必要ないです 
`#[allow(...)]` を使うのって、
「clippyちゃんが誤解しちゃうものの、正当な状況であることを明示する」わけなので、
ただ単に警告をsupressする目的で使うのはなんかうーんって顔になっちゃう

おとなしく必要ないimportは消しておきましょう、Colider足すときにimportも足せばいい

2024-09-19 15:04 UTC, LegitYew0108 commented on rust/src/world/gltf.rs
> +use godot::classes::{CollisionObject3D, GltfDocument, GltfState};
了解！

2024-09-19 15:05 UTC, LegitYew0108 commented on rust/src/world/gltf.rs
> +use godot::classes::{CollisionObject3D, GltfDocument, GltfState};
修正したよ！

2024-09-19 15:13 UTC, AsPulse approved these changes
おつかれさま～～～.ᐟ.ᐟ.ᐟ.ᐟ.ᐟ.ᐟ

2024-09-19 15:16 UTC, LegitYew0108 commented
ありがとう〜！！！
ちょっと変数ミスあったからなおした

2024-09-19 15:19 UTC, merged